### ISSUE TITLE
Awesome Books peer-to-peer code review

### ISSUE THREAD

**Issue by DebbyMiressa** [RiyaBulia12/Awesome-Book#5]
Hi @RiyaBulia12 👍 

Your project is very well done. Good job!! But try to add these optional suggestions to make your work even more polished.

- Try adding an error message when the user tries to insert an empty string in either of the input fields.
- Try changing the positioning layout of the footer from fixed to no positioning (normal flow)

**Comment by RiyaBulia12** [comment]
Thank you Debby I addressed all the issues in my latest commit. Closing the issue
